"""rename amount to cpa_amount and added new column

Revision ID: 243ca3a51c56
Revises: 
Create Date: 2026-01-25 13:43:11.411594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243ca3a51c56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('cpa_amount', sa.Float(), nullable=True))
    op.add_column('offers', sa.Column('fixed_amount', sa.Float(), nullable=True))
    op.drop_column('offers', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('offers', 'fixed_amount')
    op.drop_column('offers', 'cpa_amount')
    # ### end Alembic commands ###
